Turn off `minifyEnabled` for debug build.
It was causing `> Task :app:minifyAlphaDebugAndroidTestWithR8 FAILED` error:

```
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /home/runner/work/light-novel-library_Wenku8_Android/light-novel-library_Wenku8_Android/studio-android/LightNovelLibrary/app/build/outputs/mapping/alphaDebugAndroidTest/missing_rules.txt.
ERROR: R8: Missing class androidx.annotation.RequiresOptIn (referenced from: androidx.test.annotation.ExperimentalTestApi)
Missing class com.google.errorprone.annotations.MustBeClosed (referenced from: androidx.test.platform.tracing.Tracer$Span androidx.test.platform.tracing.Tracer$Span.beginChildSpan(java.lang.String) and 2 other contexts)
Missing class edu.umd.cs.findbugs.annotations.SuppressFBWarnings (referenced from: java.util.Map net.bytebuddy.agent.builder.LambdaFactory.CLASS_FILE_TRANSFORMERS and 117 other contexts)
Missing class java.lang.instrument.ClassDefinition (referenced from: void net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRedefinition.doApply(java.lang.instrument.Instrumentation, net.bytebuddy.agent.builder.AgentBuilder$CircularityLock, java.util.List, net.bytebuddy.agent.builder.AgentBuilder$LocationStrategy, net.bytebuddy.agent.builder.AgentBuilder$Listener) and 4 other contexts)
Missing class java.lang.instrument.ClassFileTransformer (referenced from: java.lang.instrument.ClassFileTransformer net.bytebuddy.dynamic.loading.ByteArrayClassLoader.classFileTransformer and 31 other contexts)
Missing class java.lang.instrument.IllegalClassFormatException (referenced from: java.lang.Class net.bytebuddy.dynamic.loading.ByteArrayClassLoader.findClass(java.lang.String))
Missing class java.lang.instrument.Instrumentation (referenced from: java.lang.instrument.Instrumentation net.bytebuddy.agent.ByteBuddyAgent.UNAVAILABLE and 163 other contexts)
Missing class java.lang.instrument.UnmodifiableClassException (referenced from: void net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRedefinition.doApply(java.lang.instrument.Instrumentation, net.bytebuddy.agent.builder.AgentBuilder$CircularityLock, java.util.List, net.bytebuddy.agent.builder.AgentBuilder$LocationStrategy, net.bytebuddy.agent.builder.AgentBuilder$Listener) and 10 other contexts)
Missing class java.lang.management.ManagementFactory (referenced from: java.lang.String net.bytebuddy.agent.ByteBuddyAgent$ProcessProvider$ForCurrentVm$ForLegacyVm.resolve())
Missing class java.lang.management.RuntimeMXBean (referenced from: java.lang.String net.bytebuddy.agent.ByteBuddyAgent$ProcessProvider$ForCurrentVm$ForLegacyVm.resolve())
Missing class net.bytebuddy.jar.asm.tree.AbstractInsnNode (referenced from: void net.bytebuddy.jar.asm.commons.JSRInlinerAdapter$Instantiation.<init>(net.bytebuddy.jar.asm.commons.JSRInlinerAdapter, net.bytebuddy.jar.asm.commons.JSRInlinerAdapter$Instantiation, java.util.BitSet) and 7 other contexts)
Missing class net.bytebuddy.jar.asm.tree.InsnList (referenced from: void net.bytebuddy.jar.asm.commons.JSRInlinerAdapter$Instantiation.<init>(net.bytebuddy.jar.asm.commons.JSRInlinerAdapter, net.bytebuddy.jar.asm.commons.JSRInlinerAdapter$Instantiation, java.util.BitSet) and 8 other contexts)
Missing class net.bytebuddy.jar.asm.tree.InsnNode (referenced from: void net.bytebuddy.jar.asm.commons.JSRInlinerAdapter.emitSubroutine(net.bytebuddy.jar.asm.commons.JSRInlinerAdapter$Instantiation, java.util.List, net.bytebuddy.jar.asm.tree.InsnList, java.util.List, java.util.List))
Missing class net.bytebuddy.jar.asm.tree.JumpInsnNode (referenced from: void net.bytebuddy.jar.asm.commons.JSRInlinerAdapter.emitSubroutine(net.bytebuddy.jar.asm.commons.JSRInlinerAdapter$Instantiation, java.util.List, net.bytebuddy.jar.asm.tree.InsnList, java.util.List, java.util.List) and 2 other contexts)
Missing class net.bytebuddy.jar.asm.tree.LabelNode (referenced from: net.bytebuddy.jar.asm.tree.LabelNode net.bytebuddy.jar.asm.commons.JSRInlinerAdapter$Instantiation.returnLabel and 8 other contexts)
Missing class net.bytebuddy.jar.asm.tree.LocalVariableNode (referenced from: void net.bytebuddy.jar.asm.commons.JSRInlinerAdapter.emitSubroutine(net.bytebuddy.jar.asm.commons.JSRInlinerAdapter$Instantiation, java.util.List, net.bytebuddy.jar.asm.tree.InsnList, java.util.List, java.util.List))
Missing class net.bytebuddy.jar.asm.tree.LookupSwitchInsnNode (referenced from: void net.bytebuddy.jar.asm.commons.JSRInlinerAdapter.markSubroutineWalkDFS(java.util.BitSet, int, java.util.BitSet))
Missing class net.bytebuddy.jar.asm.tree.MethodNode (referenced from: void net.bytebuddy.jar.asm.commons.JSRInlinerAdapter.<init>(int, net.bytebuddy.jar.asm.MethodVisitor, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String[]) and 4 other contexts)
Missing class net.bytebuddy.jar.asm.tree.TableSwitchInsnNode (referenced from: void net.bytebuddy.jar.asm.commons.JSRInlinerAdapter.markSubroutineWalkDFS(java.util.BitSet, int, java.util.BitSet))
Missing class net.bytebuddy.jar.asm.tree.TryCatchBlockNode (referenced from: void net.bytebuddy.jar.asm.commons.JSRInlinerAdapter.emitSubroutine(net.bytebuddy.jar.asm.commons.JSRInlinerAdapter$Instantiation, java.util.List, net.bytebuddy.jar.asm.tree.InsnList, java.util.List, java.util.List) and 5 other contexts)
Missing class org.mockito.internal.creation.bytebuddy.MockMethodDispatcher (referenced from: void org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.<init>(java.lang.instrument.Instrumentation, org.mockito.internal.util.concurrent.WeakConcurrentMap) and 7 other contexts)
Missing class org.newsclub.net.unix.AFUNIXSocket (referenced from: java.lang.Class net.bytebuddy.agent.VirtualMachine$ForHotSpot$OnUnix.assertAvailability() and 5 other contexts)
Missing class org.newsclub.net.unix.AFUNIXSocketAddress (referenced from: void net.bytebuddy.agent.VirtualMachine$ForHotSpot$OnUnix.connect())

FAILURE: Build failed with an exception.
```